/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.abhi.mycompany.aedassign_101.ui;

import com.abhi.mycompany.aedassign_101.EmployeeForm;
import com.abhi.mycompany.aedassign_101.model.Contact;
import com.abhi.mycompany.aedassign_101.model.Employee;
import java.awt.Image;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JTextArea;
import java.io.File;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhilash Gowdru Palakshappa
 */
public class CreateJpanel extends javax.swing.JPanel {

    
    /**
     * Creates new form CreateJPanel
     */
    
    public Employee employee;
    
    boolean invalidEmployee = false;
    
    public CreateJpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cEmpId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cAge = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cPositionTitle = new javax.swing.JTextField();
        cSave = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cPhoneNumber = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cImage = new javax.swing.JTextField();
        cGender = new javax.swing.JComboBox<>();
        cLevel = new javax.swing.JComboBox<>();
        cStartDate = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        cPhotoIcon = new javax.swing.JLabel();
        cTeamInfo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cErrAge = new javax.swing.JLabel();
        cErrName = new javax.swing.JLabel();
        cErrEmpId = new javax.swing.JLabel();
        cErrEmail = new javax.swing.JLabel();
        cErrDate = new javax.swing.JLabel();
        cErrPhone = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setDoubleBuffered(false);
        setFocusCycleRoot(true);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Employee");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("Name:");

        cName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cNameKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setText("Employee Id:");

        cEmpId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cEmpId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cEmpIdKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setText("Age:");

        cAge.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cAgeKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setText("Gender:");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setText("Start Date:");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel7.setText("Level");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel9.setText("Position Title:");

        cPositionTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cSave.setBackground(new java.awt.Color(153, 153, 153));
        cSave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cSave.setText("Save");
        cSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSaveActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel10.setText("Cell Number:");

        cPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cPhoneNumberKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel11.setText("Email Address:");

        cEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cEmailKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel12.setText("Image:");

        cImage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cImage.setEnabled(false);

        cGender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        cLevel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "Top", "Sky High" }));

        cStartDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        cStartDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cStartDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cStartDateKeyReleased(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Browse");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cTeamInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel13.setText("Team Info:");

        cErrAge.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        cErrAge.setForeground(new java.awt.Color(255, 0, 0));

        cErrName.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cErrName.setForeground(new java.awt.Color(255, 0, 0));

        cErrEmpId.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        cErrEmpId.setForeground(new java.awt.Color(255, 0, 0));

        cErrEmail.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        cErrEmail.setForeground(new java.awt.Color(255, 0, 0));

        cErrDate.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        cErrDate.setForeground(new java.awt.Color(255, 0, 0));

        cErrPhone.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        cErrPhone.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cName, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(cEmpId)
                    .addComponent(cAge)
                    .addComponent(cEmail)
                    .addComponent(cPositionTitle)
                    .addComponent(cPhoneNumber)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addComponent(cStartDate)
                    .addComponent(cGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cImage, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cTeamInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cErrName, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cErrAge, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cErrEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cErrDate, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cErrPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cErrEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)))
                .addComponent(cPhotoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(cSave)
                .addGap(0, 1177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cErrName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(cErrEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(cErrAge, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(cErrDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addComponent(cPhotoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cErrPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(cErrEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cSave)
                .addGap(338, 338, 338))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSaveActionPerformed
        // TODO add your handling code here:
        
        if(cName.getText().trim().equalsIgnoreCase("")
                ||cEmpId.getText().trim().equalsIgnoreCase("")
                ||cAge.getText().trim().equalsIgnoreCase("")
                ||cStartDate.getText().trim().equalsIgnoreCase("")
                ||cPositionTitle.getText().trim().equalsIgnoreCase("")
                ||cImage.getText().trim().equalsIgnoreCase("")
                ||cTeamInfo.getText().trim().equalsIgnoreCase("")){
            invalidEmployee = true;
        }else{
            invalidEmployee = false;
        }
               
        if(!invalidEmployee){
        employee = EmployeeForm.employeeDirectory.addNewEmployee();        
        employee.setNameStr(cName.getText().trim());
        employee.setEmployeeId(Integer.parseInt(cEmpId.getText().trim()));
        employee.setAge(Integer.parseInt(cAge.getText().trim()));
        employee.setGenderStr(cGender.getSelectedItem().toString());
        Date currentDate = new Date(cStartDate.getText());
        employee.setStartDate(currentDate);
        employee.setLevelStr(cLevel.getSelectedItem().toString());
        employee.setPositionTitleStr(cPositionTitle.getText().trim());
        employee.setPhoto(cImage.getText());
        employee.setTeamInfoStr(cTeamInfo.getText().trim());
        
        Contact contact = new Contact(Long.valueOf(cPhoneNumber.getText().trim()),cEmail.getText().trim());
        employee.setContact(contact);
                
        JOptionPane.showMessageDialog(this, "New Employee Saved");
        }else{
            JOptionPane.showMessageDialog(this, "Invlaid Data!!! New Employee is Not Saved");
        }
        
        cName.setText("");
        cEmpId.setText("");
        cAge.setText("");
        cStartDate.setText("");
        cPositionTitle.setText("");
        cImage.setText("");
        cTeamInfo.setText("");
        cPhoneNumber.setText("");
        cEmail.setText("");
        cPhotoIcon.setIcon(new ImageIcon(""));
        
    }//GEN-LAST:event_cSaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:       
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        cImage.setText(file.getAbsolutePath());
        
        ImageIcon image = new ImageIcon(file.getAbsolutePath());       
        Image img = image.getImage();
        img = img.getScaledInstance(cPhotoIcon.getWidth(), cPhotoIcon.getHeight(),Image.SCALE_SMOOTH);        
        cPhotoIcon.setIcon(new ImageIcon(img));
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cEmpIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cEmpIdKeyReleased
        // TODO add your handling code here:
        String regexString = "[+-]?[0-9]+";
        Pattern pattern = Pattern.compile(regexString,Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(cEmpId.getText());
        if(!matcher.matches()){
            cErrEmpId.setText("Please enter a valid Employee Id");
            invalidEmployee = true;
        }else{
            cErrEmpId.setText("");
            invalidEmployee = false;
        }
    }//GEN-LAST:event_cEmpIdKeyReleased

    private void cAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cAgeKeyReleased
        // TODO add your handling code here:
        String regexString = "^(?:(?!0)\\d{1,2}|100)$";
        Pattern pattern = Pattern.compile(regexString,Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(cAge.getText());
        if(!matcher.matches()){
            cErrAge.setText("Please enter a valid Age");
            invalidEmployee = true;
        }else{
            cErrAge.setText("");
            invalidEmployee = false;
        }
    }//GEN-LAST:event_cAgeKeyReleased

    private void cNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cNameKeyReleased
        // TODO add your handling code here:
        String regexString = "^[a-zA-Z\\s]+";
        Pattern pattern = Pattern.compile(regexString,Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(cName.getText());
        if(!matcher.matches()){
            cErrName.setText("Please enter a valid Name");
            invalidEmployee = true;
        }else{
            cErrName.setText("");
            invalidEmployee = false;
        }
    }//GEN-LAST:event_cNameKeyReleased

    private void cStartDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cStartDateKeyReleased
        // TODO add your handling code here:
        try {
        Date date = new Date(cStartDate.getText());
        String inputDate = "2016-01-07 10:11:30.500";
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss.SSS");
        dateFormat.setLenient(false);
        date = dateFormat.parse(inputDate);
        invalidEmployee = false;
        cErrDate.setText("");
        } catch (Exception IllegalArgumentException) { 
            //Code should be added to handle invalid date format
            cErrDate.setText("Valid Date Format is 29 Sep, 2022");
            invalidEmployee = true;
        }

    }//GEN-LAST:event_cStartDateKeyReleased

    private void cEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cEmailKeyReleased
        // TODO add your handling code here:
        String regexString = "^(.+)@(\\S+)$";
        Pattern pattern = Pattern.compile(regexString,Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(cEmail.getText());
        if(!matcher.matches()){
            cErrEmail.setText("Please enter a valid Email");
            invalidEmployee = true;
        }else{
            cErrEmail.setText("");
            invalidEmployee = false;
        }
    }//GEN-LAST:event_cEmailKeyReleased

    private void cPhoneNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cPhoneNumberKeyReleased
        // TODO add your handling code here:
        String regexString = "^\\d{10}$";
        Pattern pattern = Pattern.compile(regexString,Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(cPhoneNumber.getText());
        if(!matcher.matches()){
            cErrPhone.setText("Please enter a valid Phonenumber");
            invalidEmployee = true;
        }else{
            cErrPhone.setText("");
            invalidEmployee = false;
        }
    }//GEN-LAST:event_cPhoneNumberKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cAge;
    private javax.swing.JTextField cEmail;
    private javax.swing.JTextField cEmpId;
    private javax.swing.JLabel cErrAge;
    private javax.swing.JLabel cErrDate;
    private javax.swing.JLabel cErrEmail;
    private javax.swing.JLabel cErrEmpId;
    private javax.swing.JLabel cErrName;
    private javax.swing.JLabel cErrPhone;
    private javax.swing.JComboBox<String> cGender;
    private javax.swing.JTextField cImage;
    private javax.swing.JComboBox<String> cLevel;
    private javax.swing.JTextField cName;
    private javax.swing.JTextField cPhoneNumber;
    private javax.swing.JLabel cPhotoIcon;
    private javax.swing.JTextField cPositionTitle;
    private javax.swing.JButton cSave;
    private javax.swing.JFormattedTextField cStartDate;
    private javax.swing.JTextField cTeamInfo;
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
