/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package com.abhi.mycompany.aedassign_101.ui;

import com.abhi.mycompany.aedassign_101.EmployeeForm;
import com.abhi.mycompany.aedassign_101.model.Contact;
import com.abhi.mycompany.aedassign_101.model.Employee;
import java.awt.Image;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Abhilash Gowdru Palakshappa
 */
public class ViewJpanel extends javax.swing.JPanel {
   
    /** Creates new form ViewJpanel */
    
    private boolean invalidEmployee = false;
    
    public ViewJpanel() {
        initComponents();
               
        populateTable();
        
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vEmpDetails = new javax.swing.JTable();
        vPhotoIcon = new javax.swing.JLabel();
        jButtonView = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        vPhoneNumber = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        vEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        vImage = new javax.swing.JTextField();
        vStartDate = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        vName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        vEmpId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        vAge = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        vPositionTitle = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        vTeamInfo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        vGender = new javax.swing.JTextField();
        vLevel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        tfSearch = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        vErrName = new javax.swing.JLabel();
        vErrGender = new javax.swing.JLabel();
        vErrEmpId = new javax.swing.JLabel();
        vErrAge = new javax.swing.JLabel();
        vErrGender1 = new javax.swing.JLabel();
        vErrStartDate = new javax.swing.JLabel();
        vErrLevel = new javax.swing.JLabel();
        vErrPhoneNumber = new javax.swing.JLabel();
        vErrEmail = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Details");

        vEmpDetails.setBackground(new java.awt.Color(153, 153, 153));
        vEmpDetails.setBorder(new javax.swing.border.MatteBorder(null));
        vEmpDetails.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        vEmpDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Employee Id", "Age", "Gender", "Start Date", "Level", "Team Info", "Position Title", "Cell Number", "Email Address", "Image"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        vEmpDetails.setFocusable(false);
        vEmpDetails.setGridColor(new java.awt.Color(0, 0, 0));
        vEmpDetails.setIntercellSpacing(new java.awt.Dimension(1, 1));
        vEmpDetails.setPreferredSize(new java.awt.Dimension(900, 500));
        vEmpDetails.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(vEmpDetails);

        jButtonView.setBackground(new java.awt.Color(153, 153, 153));
        jButtonView.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButtonView.setText("View");
        jButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(153, 153, 153));
        jButtonDelete.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        vPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        vPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vPhoneNumberKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel11.setText("Email Address:");

        vEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        vEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vEmailKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel12.setText("Image:");

        vImage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        vImage.setEnabled(false);

        vStartDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        vStartDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        vStartDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vStartDateKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("Name:");

        vName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        vName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vNameKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setText("Employee Id:");

        vEmpId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        vEmpId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vEmpIdKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setText("Age:");

        vAge.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        vAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vAgeKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setText("Gender:");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setText("Start Date:");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel7.setText("Level");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel9.setText("Position Title:");

        vPositionTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel10.setText("Cell Number:");

        vTeamInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel13.setText("Team Info:");

        vGender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        vGender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vGenderKeyReleased(evt);
            }
        });

        vLevel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        vLevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vLevelKeyReleased(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton1.setText("Browse");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonUpdate.setBackground(new java.awt.Color(153, 153, 153));
        jButtonUpdate.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        tfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSearchKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel8.setText("Search");

        vErrName.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        vErrName.setForeground(new java.awt.Color(255, 0, 0));

        vErrGender.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        vErrGender.setForeground(new java.awt.Color(255, 0, 0));

        vErrEmpId.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        vErrEmpId.setForeground(new java.awt.Color(255, 0, 0));

        vErrAge.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        vErrAge.setForeground(new java.awt.Color(255, 0, 0));

        vErrGender1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        vErrGender1.setForeground(new java.awt.Color(255, 0, 0));

        vErrStartDate.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        vErrStartDate.setForeground(new java.awt.Color(255, 0, 0));

        vErrLevel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        vErrLevel.setForeground(new java.awt.Color(255, 0, 0));

        vErrPhoneNumber.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        vErrPhoneNumber.setForeground(new java.awt.Color(255, 0, 0));

        vErrEmail.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        vErrEmail.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vName, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vAge, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vGender, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(vErrGender1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(vErrGender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(vErrEmpId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(vErrName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jButtonView)
                                .addGap(57, 57, 57)
                                .addComponent(jButtonDelete))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vErrLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vErrStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vErrAge, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(vPhotoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(vErrPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vErrEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1368, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jButtonUpdate)))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonView))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(vName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vErrName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(vErrEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vErrAge, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(vAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vErrGender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(vGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(vStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(vErrStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(vErrGender1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(vLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(vErrLevel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(vPhotoIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(vErrPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(vErrEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonUpdate)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewActionPerformed
        // TODO add your handling code here:
        
        int selectedIndexRow = vEmpDetails.getSelectedRow();
        
        if(selectedIndexRow<0){
            JOptionPane.showMessageDialog(this, "Please Select the row to be Viewd");
            return;
        }
                
        DefaultTableModel model  = (DefaultTableModel)vEmpDetails.getModel();
        
        Employee employee = getData(model,selectedIndexRow);
        
        System.out.println(employee.toString());
        
        vName.setText(employee.getNameStr());
        vEmpId.setText(Integer.toString(employee.getEmployeeId()));
        vAge.setText(Integer.toString(employee.getAge()));
        vGender.setText(employee.getGenderStr());
        vStartDate.setText(employee.getStartDate().toString());
        vLevel.setText(employee.getLevelStr());
        vPositionTitle.setText(employee.getPositionTitleStr());
        vTeamInfo.setText(employee.getTeamInfoStr());
        vImage.setText(employee.getPhoto());
        vPhoneNumber.setText(employee.getContact().getPhoneNumberStr().toString());
        vEmail.setText(employee.getContact().getEmailStr());
               
        ImageIcon image = new ImageIcon(employee.getPhoto());
        
        Image img = image.getImage();
        img = img.getScaledInstance(vPhotoIcon.getWidth(), vPhotoIcon.getHeight(),Image.SCALE_SMOOTH);
        
        vPhotoIcon.setIcon(new ImageIcon(img));
        
    }//GEN-LAST:event_jButtonViewActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        int selectedIndexRow = vEmpDetails.getSelectedRow();
        
        if(selectedIndexRow<0){
            JOptionPane.showMessageDialog(this, "Please Select the row to be Deleted");
            return;
        }
        
        DefaultTableModel model  = (DefaultTableModel)vEmpDetails.getModel();
        
        Employee employee = getData(model,selectedIndexRow);
             
        EmployeeForm.employeeDirectory.deleteEmployee(employee);
                    
        JOptionPane.showMessageDialog(this, "Deleted a Employee");
        
        populateTable();
        
        vName.setText("");
        vEmpId.setText("");
        vAge.setText("");
        vGender.setText("");
        vStartDate.setText("");
        vLevel.setText("");
        vPositionTitle.setText("");
        vTeamInfo.setText("");
        vImage.setText("");
        vPhoneNumber.setText("");
        vEmail.setText("");
        vPhotoIcon.setIcon(new ImageIcon());
        
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        vImage.setText(file.getAbsolutePath());

        ImageIcon image = new ImageIcon(file.getAbsolutePath());
        Image img = image.getImage();
        img = img.getScaledInstance(vPhotoIcon.getWidth(), vPhotoIcon.getHeight(),Image.SCALE_SMOOTH);
        vPhotoIcon.setIcon(new ImageIcon(img));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        if(!invalidEmployee)
        {        
            int selectedIndexRow = vEmpDetails.getSelectedRow();

            if(selectedIndexRow<0){
                JOptionPane.showMessageDialog(this, "Please Select the row to Update it");
                return;
            }

            DefaultTableModel model  = (DefaultTableModel)vEmpDetails.getModel();

            Employee selectedEmployee = getData(model,selectedIndexRow);

            Employee employeeFromList = EmployeeForm.employeeDirectory.getEmployee(selectedEmployee);

            setData(employeeFromList);

            populateTable();

            JOptionPane.showMessageDialog(this, "Updated a Employee");
        }else{
            JOptionPane.showMessageDialog(this, "Invlaid Data!!! Employee Update is Not Saved");
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void tfSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyPressed
        // TODO add your handling code here:
        
        DefaultTableModel model  = (DefaultTableModel)vEmpDetails.getModel();
        
        TableRowSorter<TableModel>  rowSorter = new TableRowSorter<>(vEmpDetails.getModel());
        
        vEmpDetails.setRowSorter(rowSorter);
        
        //Refernce from Stack Overflow
        tfSearch.getDocument().addDocumentListener(new DocumentListener(){

            @Override
            public void insertUpdate(DocumentEvent e) {
                String searchText = tfSearch.getText();

                if (searchText.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchText));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String searchText = tfSearch.getText();

                if (searchText.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchText));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates
            }

        });
        
    }//GEN-LAST:event_tfSearchKeyPressed

    private void vNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vNameKeyReleased
        // TODO add your handling code here:
        String regexString = "^[a-zA-Z\\s]+";
        Pattern pattern = Pattern.compile(regexString,Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(vName.getText());
        if(!matcher.matches()){
            vErrName.setText("Please enter a valid Name");
            invalidEmployee = true;
        }else{
            vErrName.setText("");
            invalidEmployee = false;
        }
    }//GEN-LAST:event_vNameKeyReleased

    private void vEmpIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vEmpIdKeyReleased
        // TODO add your handling code here:
        String regexString = "[+-]?[0-9]+";
        Pattern pattern = Pattern.compile(regexString,Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(vEmpId.getText());
        if(!matcher.matches()){
            vErrEmpId.setText("Please enter a valid Employee Id");
            invalidEmployee = true;
        }else{
            vErrEmpId.setText("");
            invalidEmployee = false;
        }
    }//GEN-LAST:event_vEmpIdKeyReleased

    private void vAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vAgeKeyReleased
        // TODO add your handling code here:
        String regexString = "^(?:(?!0)\\d{1,2}|100)$";
        Pattern pattern = Pattern.compile(regexString,Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(vAge.getText());
        if(!matcher.matches()){
            vErrAge.setText("Please enter a valid Age");
            invalidEmployee = true;
        }else{
            vErrAge.setText("");
            invalidEmployee = false;
        }
    }//GEN-LAST:event_vAgeKeyReleased

    private void vStartDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vStartDateKeyReleased
        // TODO add your handling code here:
        try {
        Date date = new Date(vStartDate.getText());
        String inputDate = "2016-01-07 10:11:30.500";
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss.SSS");
        dateFormat.setLenient(false);
        date = dateFormat.parse(inputDate);
        invalidEmployee = false;
        vErrStartDate.setText("");
        } catch (Exception IllegalArgumentException) { 
            //Code should be added to handle invalid date format
            vErrStartDate.setText("Valid Date Format is 29 Sep, 2022");
            invalidEmployee = true;
        }
    }//GEN-LAST:event_vStartDateKeyReleased

    private void vPhoneNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vPhoneNumberKeyReleased
        // TODO add your handling code here:
        String regexString = "^\\d{10}$";
        Pattern pattern = Pattern.compile(regexString,Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(vPhoneNumber.getText());
        if(!matcher.matches()){
            vErrPhoneNumber.setText("Please enter a valid Phonenumber");
            invalidEmployee = true;
        }else{
            vErrPhoneNumber.setText("");
            invalidEmployee = false;
        }
    }//GEN-LAST:event_vPhoneNumberKeyReleased

    private void vEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vEmailKeyReleased
        // TODO add your handling code here:
        String regexString = "^(.+)@(\\S+)$";
        Pattern pattern = Pattern.compile(regexString,Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(vEmail.getText());
        if(!matcher.matches()){
            vErrEmail.setText("Please enter a valid Email");
            invalidEmployee = true;
        }else{
            vErrEmail.setText("");
            invalidEmployee = false;
        }
    }//GEN-LAST:event_vEmailKeyReleased

    private void vGenderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vGenderKeyReleased
        // TODO add your handling code here:
        String regexString = "^M(ale)?$|^F(emale)?$|^Other?$";
        Pattern pattern = Pattern.compile(regexString,Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(vGender.getText());
        if(!matcher.matches()){
            vErrGender.setText("Only Male|Female|Other");
            invalidEmployee = true;
        }else{
            vErrGender.setText("");
            invalidEmployee = false;
        }
    }//GEN-LAST:event_vGenderKeyReleased

    private void vLevelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vLevelKeyReleased
        // TODO add your handling code here:
        String regexString = "^Low?$|^Medium?$|^High?$|^Sky High?$";
        Pattern pattern = Pattern.compile(regexString,Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(vLevel.getText());
        if(!matcher.matches()){
            vErrLevel.setText("Only Low|Medium|High|Sky High");
            invalidEmployee = true;
        }else{
            vErrLevel.setText("");
            invalidEmployee = false;
        }
    }//GEN-LAST:event_vLevelKeyReleased

    private Employee getData(DefaultTableModel model,int selectedIndexRow){
        
        Employee employee = new Employee();
        employee.setNameStr((String)model.getValueAt(selectedIndexRow, 0));
        employee.setEmployeeId((int)model.getValueAt(selectedIndexRow, 1));
        employee.setAge((int)model.getValueAt(selectedIndexRow, 2));
        employee.setGenderStr(model.getValueAt(selectedIndexRow, 3).toString());
        employee.setStartDate( (Date) model.getValueAt(selectedIndexRow, 4));
        employee.setLevelStr( model.getValueAt(selectedIndexRow, 5).toString());
        employee.setTeamInfoStr(model.getValueAt(selectedIndexRow, 6).toString());
        employee.setPositionTitleStr(model.getValueAt(selectedIndexRow, 7).toString());
        employee.setPhoto(model.getValueAt(selectedIndexRow, 10).toString());        
        Contact contact = new Contact();
        
        contact.setPhoneNumberStr((Long) model.getValueAt(selectedIndexRow, 8));
        contact.setEmailStr(model.getValueAt(selectedIndexRow, 9).toString());
        
        employee.setContact(contact);
                
        return employee;
    }
    
        private void populateTable() {

        DefaultTableModel model  = (DefaultTableModel)vEmpDetails.getModel();
        model.setRowCount(0);
        
        for(Employee emp : EmployeeForm.employeeDirectory.getDirectorty()){
            
            Object[] row = new Object[12];
            row[0] = emp.getNameStr();
            row[1] = emp.getEmployeeId();
            row[2] = emp.getAge();
            row[3] = emp.getGenderStr();
            row[4] = emp.getStartDate();
            row[5] = emp.getLevelStr();
            row[6] = emp.getTeamInfoStr();
            row[7] = emp.getPositionTitleStr();
            row[8] = emp.getContact().getPhoneNumberStr();
            row[9] = emp.getContact().getEmailStr();
            row[10] = emp.getPhoto();
            
            model.addRow(row);
        }
            
    }

    private void setData(Employee employeeFromList) {
        
        employeeFromList.setNameStr(vName.getText());        
        employeeFromList.setEmployeeId(Integer.parseInt(vEmpId.getText()));
        employeeFromList.setAge(Integer.parseInt(vAge.getText()));
        employeeFromList.setGenderStr(vGender.getText());
        Date date = new Date(vStartDate.getText());
        employeeFromList.setStartDate(date);
        employeeFromList.setLevelStr(vLevel.getText());
        employeeFromList.setTeamInfoStr(vTeamInfo.getText());
        employeeFromList.setPositionTitleStr(vPositionTitle.getText());
        employeeFromList.setPhoto(vImage.getText());        
        Contact contact = new Contact();
        
        contact.setPhoneNumberStr(Long.valueOf(vPhoneNumber.getText()));
        contact.setEmailStr(vEmail.getText());
        
        employeeFromList.setContact(contact);
              
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtonView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField vAge;
    private javax.swing.JTextField vEmail;
    private javax.swing.JTable vEmpDetails;
    private javax.swing.JTextField vEmpId;
    private javax.swing.JLabel vErrAge;
    private javax.swing.JLabel vErrEmail;
    private javax.swing.JLabel vErrEmpId;
    private javax.swing.JLabel vErrGender;
    private javax.swing.JLabel vErrGender1;
    private javax.swing.JLabel vErrLevel;
    private javax.swing.JLabel vErrName;
    private javax.swing.JLabel vErrPhoneNumber;
    private javax.swing.JLabel vErrStartDate;
    private javax.swing.JTextField vGender;
    private javax.swing.JTextField vImage;
    private javax.swing.JTextField vLevel;
    private javax.swing.JTextField vName;
    private javax.swing.JTextField vPhoneNumber;
    private javax.swing.JLabel vPhotoIcon;
    private javax.swing.JTextField vPositionTitle;
    private javax.swing.JFormattedTextField vStartDate;
    private javax.swing.JTextField vTeamInfo;
    // End of variables declaration//GEN-END:variables

}